apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: launchpad-xsuaa
  namespace: development
  labels:
    sample: launchpad
spec:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    xsappname: launchpad
    tenant-mode: dedicated
    oauth2-configuration:
      redirect-uris:
        # callback
        - "https://launchpad.c-4dc2769.kyma.ondemand.com/**"
        - "http://localhost:5000/**"
---
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: launchpad-xsuaa
  namespace: development
  labels:
    sample: launchpad
spec:
  serviceInstanceName: launchpad-xsuaa